export const USER_ADDED = 'USER_ADDED'

export const USER_REMOVED = 'USER_REMOVED'

export const USER_INPUT = 'USER_INPUT'

export const USER_CALLING = 'USER_CALLING'

export const CONNECTED_USER_ADDED = 'CONNECTED_USER_ADDED'
